# Generated by Django 5.0.2 on 2024-02-20 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pins', '0003_remove_like_post_like_pin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
