# Generated by Django 5.0.2 on 2024-02-23 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        ('pins', '0005_pin_ideas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pin',
            name='ideas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pins', to='ideas.idea'),
        ),
    ]
