# Generated by Django 5.0.2 on 2024-02-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        ('pins', '0006_alter_pin_ideas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pin',
            name='ideas',
        ),
        migrations.AddField(
            model_name='pin',
            name='ideas',
            field=models.ManyToManyField(related_name='pins', to='ideas.idea'),
        ),
    ]
