# Generated by Django 5.0.2 on 2024-02-19 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_pin_alter_comment_user'),
        ('pins', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pins.pin'),
        ),
    ]
