# Generated by Django 5.0.2 on 2024-03-02 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=1012, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=4, message='O nome de usuário deve ter no mínimo 4 caracteres.')]),
        ),
    ]
